# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wc}
  s.version = "0.99.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paolo Perego"]
  s.date = %q{2011-07-05}
  s.default_executable = %q{wc}
  s.description = %q{your ruby word counter experience}
  s.email = %q{thesp0nge@gmail.com}
  s.executables = ["wc"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/wc",
    "doc/String.html",
    "doc/Wc.html",
    "doc/Wc/Engine.html",
    "doc/Wc/Reader.html",
    "doc/_index.html",
    "doc/class_list.html",
    "doc/classes/Wc.html",
    "doc/classes/Wc.src/M000001.html",
    "doc/classes/Wc.src/M000002.html",
    "doc/classes/Wc.src/M000003.html",
    "doc/classes/Wc.src/M000004.html",
    "doc/classes/Wc.src/M000005.html",
    "doc/classes/Wc.src/M000006.html",
    "doc/created.rid",
    "doc/css/common.css",
    "doc/css/full_list.css",
    "doc/css/style.css",
    "doc/file.README.html",
    "doc/file_list.html",
    "doc/files/lib/wc_rb.html",
    "doc/fr_class_index.html",
    "doc/fr_file_index.html",
    "doc/fr_method_index.html",
    "doc/frames.html",
    "doc/index.html",
    "doc/js/app.js",
    "doc/js/full_list.js",
    "doc/js/jquery.js",
    "doc/method_list.html",
    "doc/rdoc-style.css",
    "doc/top-level-namespace.html",
    "lib/wc.rb",
    "lib/wc/engine.rb",
    "lib/wc/reader.rb",
    "spec/spec_helper.rb",
    "spec/wc_spec.rb",
    "wc.gemspec"
  ]
  s.homepage = %q{http://github.com/thesp0nge/wc}
  s.licenses = ["new BSD License"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{your ruby word counter experience}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

